[package]
name = "rtoy-driver"
version = "0.0.1"
edition = "2021"

[dependencies]
rtoy-lexer = { path = "../lexer" }
rtoy-ast = { path = "../ast" }
rtoy-tokenstream-lowering = { path = "../tokenstream-lowering" }
rtoy-resolve = { path = "../resolve" }
rtoy-span = { path = "../span" }
rtoy-expand = { path = "../expand" }
